services:
  source_postgres:
    image: postgres:15.6
    ports:
      - 5433:5432
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
  dest_postgres:
    image: postgres:15.6
    ports:
      - 5434:5432
    networks:
      - elt_network
    environment:
      POSTGRES_DB: dest_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_secret
  # elt_script:
  #   build:
  #     context: ./elt-de
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - source_postgres
  #     - dest_postgres
  #   command: ["python", "elt_script.py"]
  #   networks:
  #     - elt_network
  # dbt:
  #   image: ghcr.io/dbt-labs/dbt-postgres:1.7.13
  #   depends_on:
  #     elt_script:
  #       condition: service_completed_successfully
  #   command: ["run" , "--profiles-dir", "/root", "--project-dir", "/dbt",]
  #   networks:
  #     - elt_network
  #   volumes:
  #     - ./transformations:/dbt
  #     - ~/.dbt:/root
  #   environment:
  #     DBT_PROFILE: default
  #     DBT_TARGET: dev

  postgres:
    image: postgres:15.6
    networks:
      - elt_network
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
  
  init-airflow:
    image: apache/airflow:2.9.1
    depends_on:
      - postgres
    networks:
      - elt_network
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: >
      bash -c "airflow db migrate && 
               airflow users create --username airflow --password password --firstname John --lastname Doe --role Admin --email admin@example.com"

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      postgres:
        condition: service_healthy
      init-airflow:
        condition: service_completed_successfully
    networks:
      - elt_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./elt-de:/opt/airflow/elt-de
      - ./transformations:/opt/dbt
      - ~/.dbt:/root/.dbt
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=QHf3HBb8yTSWlax7tBpc89hdzWRBYKnklm0lSKHm4uA=
      - AIRFLOW__WEBSERVER__DEFAULT__USER_USERNAME=airflow
      - AIRFLOW__WEBSERVER__DEFAULT__USER_PASSWORD=password
      - AIRFLOW_WWW_USER_USERNAME=airflow
      - AIRFLOW_WWW_USER_PASSWORD=password
      - AIRFLOW__WEBSERVER__SECRET_KEY=secret
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      postgres:
        condition: service_healthy
      init-airflow:
        condition: service_completed_successfully
    networks:
      - elt_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./elt-de:/opt/airflow/elt-de
      - ./transformations:/dbt
      - ~/.dbt:/root/.dbt
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=QHf3HBb8yTSWlax7tBpc89hdzWRBYKnklm0lSKHm4uA=
      - AIRFLOW__WEBSERVER__DEFAULT__USER_USERNAME=airflow
      - AIRFLOW__WEBSERVER__DEFAULT__USER_PASSWORD=password
      - AIRFLOW_WWW_USER_USERNAME=airflow
      - AIRFLOW_WWW_USER_PASSWORD=password
      - AIRFLOW__WEBSERVER__SECRET_KEY=secret
    command: scheduler

networks:
  elt_network:
    driver: bridge
